config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root to: redirect('/session/new', status: 302)

  resources :users, only: %i[new create] do
    # This route is related to admin section, but can't be placed under /admin
    # because of https://github.com/thoughtbot/administrate/issues/481
    resources :details_deliveries, only: :create
  end
  resource :session, only: %i[new create destroy]

  namespace :admin do
    resources :users
    root to: redirect('/admin/users', status: 302)
  end

  get 'home' => 'homes#show'

  Sidekiq::Web.use AuthorizationMiddleware
  mount Sidekiq::Web => '/sidekiq'
end

ActiveSupport::Notifications.instrument 'routes_loaded.application'

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  ROLES = %w[user admin].freeze

  mount_uploader :avatar, AvatarUploader

  validates :role, inclusion: ROLES
  validates :email, uniqueness: true, format: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
  validates :email, :full_name, :birth_date, :small_biography, presence: true
  validates :password, length: {minimum: 8}, allow_nil: true

  has_secure_password

  def admin?
    role == 'admin'
  end
end

app/controllers/admin/application_controller.rb
module Admin
  class ApplicationController < Administrate::ApplicationController
    include AuthenticationConcern
    include AuthorizationConcern
    before_action :require_authentication, :require_admin
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include AuthenticationConcern
  include AuthorizationConcern
  protect_from_forgery with: :exception
end

app/controllers/concerns/authentication_concern.rb
module AuthenticationConcern
  extend ActiveSupport::Concern

  LoggedInUserNotFound = Class.new StandardError

  included do
    if ancestors.map(&:name).include? 'ActionController::Base'
      helper_method :user_logged_in?, :current_user
      rescue_from LoggedInUserNotFound, with: :log_out
    end
  end

  private

  def log_in(user)
    session[:user_id] = user.id
    redirect_to logged_in_redirect_path(user), notice: t('sessions.create.success')
  end

  def log_out
    session.delete :user_id
    redirect_to new_session_path, notice: t('sessions.destroy.success')
  end

  def user_logged_in?
    session[:user_id].present?
  end

  def current_user
    @current_user ||= ::User.find session[:user_id]
  rescue ActiveRecord::RecordNotFound
    raise LoggedInUserNotFound, 'User saved in session was not found'
  end

  def logged_in_redirect_path(user)
    user.admin? ? admin_users_path : home_path
  end
end

app/controllers/concerns/authentication_controller_methods.rb
module AuthenticationControllerMethods
  extend ActiveSupport::Concern

  LoggedInUserNotFound = Class.new StandardError

  included do
    helper_method :user_logged_in?, :current_user
    rescue_from LoggedInUserNotFound, with: :log_out
  end

  def user_logged_in?
    session[:user_id].present?
  end

  def current_user
    @current_user ||= User.find session[:user_id]
  rescue ActiveRecord::RecordNotFound
    raise LoggedInUserNotFound, 'User saved in session was not found'
  end

  def log_out
    session.delete :user_id
    redirect_to new_session_path, notice: t('sessions.destroy.success')
  end

  def require_authentication!
    redirect_to new_session_path, alert: t('application.authentication_required') unless user_logged_in?
  end
end

app/controllers/concerns/authentication_methods.rb
module AuthenticationMethods
  extend ActiveSupport::Concern

  LoggedInUserNotFound = Class.new StandardError

  included do
    helper_method :user_logged_in?, :current_user
    rescue_from LoggedInUserNotFound, with: :log_out
  end

  def user_logged_in?
    session[:user_id].present?
  end

  def current_user
    @current_user ||= User.find session[:user_id]
  rescue ActiveRecord::RecordNotFound
    raise LoggedInUserNotFound, 'User saved in session was not found'
  end

  def log_out
    session.delete :user_id
    redirect_to new_session_path, notice: t('sessions.destroy.success')
  end

  def require_authentication!
    redirect_to new_session_path, alert: t('application.authentication_required') unless user_logged_in?
  end
end

app/controllers/concerns/authorization_concern.rb
module AuthorizationConcern
  private

  def require_authentication
    redirect_to new_session_path, alert: t('application.authentication_required') unless user_logged_in?
  end

  def require_admin
    redirect_to root_path, alert: t('application.admin_required') unless current_user.admin?
  end
end

app/controllers/concerns/authorization_methods.rb
module AuthorizationMethods
  def require_admin!
    redirect_to root_path, alert: t('application.admin_required') unless current_user.admin?
  end
end

app/controllers/details_deliveries_controller.rb
class DetailsDeliveriesController < ApplicationController
  include AuthorizationConcern

  before_action :require_authentication, :require_admin, :require_user

  def create
    AdminMailer.user_details(@user).deliver_later
    flash.notice = t '.success'
    redirect_to admin_user_path @user
  end

  private

  def require_user
    @user = User.select(:id).find(params[:user_id])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :require_authentication
  def show; end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to logged_in_redirect_path(current_user) if user_logged_in?
  end

  def create
    result = Authentication::Check.call session_params

    if result.success?
      log_in result.user
    else
      flash.now.alert = result.message
      render :new
    end
  end

  def destroy
    log_out
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    result = Authentication::RegisterUser.call user_params

    if result.success?
      redirect_to new_session_path, notice: t('.success')
    else
      @user = result.user
      flash.now.alert = t '.failure'
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :email,
      :password,
      :password_confirmation,
      :full_name,
      :birth_date,
      :small_biography,
      :avatar
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  BOOTSTRAP_FLASH_CLASSES = {notice: 'alert-success', alert: 'alert-danger'}.freeze

  def bootstrap_class_for_flash(type)
    BOOTSTRAP_FLASH_CLASSES.fetch type.to_sym, type.to_s
  end
end

app/views/admin/application/_navigation.html.erb
<%#
# Navigation

This partial is used to display the navigation in Administrate.
By default, the navigation contains navigation links
for all resources in the admin dashboard,
as defined by the routes in the `admin/` namespace
%>

<nav class="navigation" role="navigation">
  <% Administrate::Namespace.new(namespace).resources.each do |resource| %>
    <%= link_to(
      display_resource_name(resource),
      [namespace, resource_index_route_key(resource)],
      class: "navigation__link navigation__link--#{nav_link_state(resource)}"
    ) if valid_action? :index, resource  %>
  <% end %>

  <hr />
  <%= link_to 'Sidekiq', sidekiq_web_path, class: 'navigation__link' %>
  <%= link_to 'Log out', session_path, method: :delete, class: 'navigation__link' %>
</nav>

app/views/admin/users/show.html.erb
<%#
# Show

This view is the template for the show page.
It renders the attributes of a resource,
as well as a link to its edit page.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Show][1].
  Contains methods for accessing the resource to be displayed on the page,
  as well as helpers for describing how each attribute of the resource
  should be displayed.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Show
%>

<% content_for(:title) { t("administrate.actions.show_resource", name: page.page_title) } %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title">
    <%= content_for(:title) %>
  </h1>

  <div>
    <%= link_to(
      t('.send_user_details_by_email'),
      user_details_deliveries_path(page.resource),
      method: :post,
      class: 'button',
    ) %>
    <%= link_to(
      t("administrate.actions.edit_resource", name: page.page_title),
      [:edit, namespace, page.resource],
      class: "button",
    ) if valid_action?(:edit) && show_action?(:edit, page.resource) %>
  </div>
</header>

<section class="main-content__body">
  <dl>
    <% page.attributes.each do |attribute| %>
      <dt class="attribute-label" id="<%= attribute.name %>">
      <%= t(
        "helpers.label.#{resource_name}.#{attribute.name}",
        default: attribute.name.titleize,
      ) %>
      </dt>

      <dd class="attribute-data attribute-data--<%=attribute.html_class%>"
          ><%= render_field attribute, page: page %></dd>
    <% end %>
  </dl>
</section>

app/views/application/_flash_messages.html.haml
- flash.each do |type, message|
  .alert.alert-dismissable.fade.show{class: bootstrap_class_for_flash(type), role: 'alert'}
    %button.close.align-top{'data-dismiss' => 'alert', 'aria-label' => 'Close'}
      %span{'aria-hidden' => true} &times;
    = message

app/views/application/_header.html.haml
%nav.navbar.navbar-expand-sm.navbar-light.bg-light.shadow-sm
  = link_to t('application_name'), root_path, class: 'navbar-brand'

  %ul.navbar-nav.ml-auto
    - if user_logged_in?
      %li.nav-item
        = link_to t('.log_out'), session_path, method: :delete, class: 'nav-link'
    - else
      %li.nav-item
        = link_to t('.log_in'), new_session_path, class: 'nav-link'
      %li.nav-item
        = link_to t('.register'), new_user_path, class: 'nav-link'

app/views/fields/carrierwave_field/_form.html.erb
<div class="field-unit__label">
  <%= f.label field.attribute %>
</div>
<div class="field-unit__field">
  <%= image_tag field.thumbnail_url if field.data.present? %>
  <%= f.file_field field.attribute %>
</div>

app/views/fields/carrierwave_field/_index.html.erb
<%= image_tag field.thumbnail_url %>

app/views/fields/carrierwave_field/_show.html.erb
<%= image_tag field.url if field.data.present? %>

app/views/homes/show.html.haml
%h1= t '.title'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type'}/
    %meta{charset: 'utf-8'}/
    %meta{content: 'width=device-width, initial-scale=1, shrink-to-fit=no', name: 'viewport'}/

    %title= t 'application_name'

    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %header
      = render 'header'
    %main
      %section.row
        .col-10.col-sm-fixed-width.mx-auto
          .mt-2
            = render 'flash_messages'
      .container
        .row
          .col-10.col-sm-fixed-width.mx-auto
            .my-4
              = yield

app/views/users/new.html.haml
%h1= t('.title')

= simple_form_for @user, html: {class: 'mt-4'} do |f|
  = f.error_notification
  = f.input :email
  = f.input :password, required: true
  = f.input :password_confirmation, required: true
  = f.input :full_name
  = f.input :birth_date, as: :string
  = f.input :small_biography
  = f.input :avatar, wrapper: :horizontal_file
  .mt-4
    = f.button :submit, t('.submit'), class: 'btn-primary'